### ISSUE TITLE
Player Controller

### ISSUE THREAD

**Issue by BLaZeKiLL** [BLaZeKiLL/VloxyEngine#103]
With colliders done, we can start with a better player controller
- [] First person
- [] Third person
- [] Fly around

**Comment by AldeRoberge** [comment]
I recommend https://assetstore.unity.com/packages/tools/physics/kinematic-character-controller-99131

![image](https://github.com/BLaZeKiLL/VloxyEngine/assets/4276275/226c342b-ace0-4fa9-a279-06f2591c9586)

I use it with my voxel game right now, and it's pretty good, even for a VR controlled player.

If we can get the following to work :

* Colliders for Chunks
* Player First Person Controller
* Set Voxel API

We'd have a very good base to start off.

**Comment by BLaZeKiLL** [comment]
I'll take a look, for now, something like Minecraft (first-person and fly-around) that you can toggle on demand would be nice since colliders are done we can implement runtime voxel manipulation API's (need to figure out and efficient algorithm for setting data in the compressed voxel data structure, we could even move to octrees that would allow LOD's also in the future).
